### ISSUE TITLE
How to add the go-ssb-room plugin to go-ssb-pub 

### ISSUE THREAD

**Issue by Scott20222** [staltz/ssb-room#33]
Hello, we have installed go-ssb pub. Now we want to integrate go-ssb-room into pub. Is there an integration method? In addition, do the integrated pub and room have their own SSB id or only one SSB id? Well, if there are two SSB id , is it supported by the user who chooses which one to use for communication?thanks.

**Comment by staltz** [comment]
Same as https://github.com/cryptoscope/ssb/issues/139#issuecomment-1016196164
