### ISSUE TITLE
SSL support (out of the box)

### ISSUE THREAD

**Issue by staltz** [staltz/ssb-room#8]
I didn't add SSL originally for two reasons: too much work (I wanted to get Rooms released asap), and uncertainty about SSL for plain IP addresses. When a user installs their first ssb-room using the D.O. installer, they get a webapp running at a certain IP address. This may remain like this if they don't have a domain or don't set up a domain. I have no experience with setting up SSL for IP addresses, but maybe that's possible?

I'm happy if someone could make a PR to add easy SSL support, the main requirement being that this has to keep the *no-terminal* (and no dev skills) D.O. installer process still a no-terminal experience. 

I suppose we could run letsencrypt in one of these two files

- https://github.com/staltz/ssb-room/blob/master/app.yml
- https://github.com/staltz/ssb-room/blob/master/install.sh

**Comment by leo-lb** [comment]
PR: #9

**Comment by leo-lb** [comment]
#9 was merged! This can be closed now, I believe :-)
